import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import Canvas from '../components/canvas'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="hero min-h-screen bg-base-200">
          <div className="hero-content text-center">
            <div className="max-w-md">
              <h1 className="text-5xl font-bold">НейроХудожник</h1>
              <p className="py-6 text-base">Создавайте с нами произведения искусства!</p>
              <a href='#authors' role="button" className="btn btn-primary">Начать</a>
            </div>
          </div>
        </div>
        <div className='min-h-screen grid' id='canvas'>
          <Canvas className='h-[100%]' />
        </div>
        <Footer />
      </main>
    </>
  )
}
